#!/usr/bin/env bash
# Generates COMMANDS.md from installed framework manifests.
# Prints post-install manual action blocks.

# generate_commands_md MANIFESTS_DIR FRAMEWORK_ID...
# Writes COMMANDS.md content to stdout.
generate_commands_md() {
    local manifests_dir="$1"
    shift
    local frameworks=("$@")

    echo "# Commands"
    echo ""
    echo "Generated by ClaudeKit init. Do not edit manually — regenerated on update."
    echo ""
    echo "| Command | Description |"
    echo "|---------|-------------|"

    for fw in "${frameworks[@]}"; do
        local manifest="$manifests_dir/${fw}.json"
        if [[ ! -f "$manifest" ]]; then
            continue
        fi
        jq -r '.commands[] | "| `\(.name)` | \(.description) |"' "$manifest"
    done
}

# print_manual_actions MANIFESTS_DIR FRAMEWORK_ID...
# Prints manual action blocks to stdout. Action IDs are assigned sequentially
# across all installed frameworks.
print_manual_actions() {
    local manifests_dir="$1"
    shift
    local frameworks=("$@")
    local counter=1

    for fw in "${frameworks[@]}"; do
        local manifest="$manifests_dir/${fw}.json"
        if [[ ! -f "$manifest" ]]; then
            continue
        fi

        local action_count
        action_count=$(jq '.post_install_actions | length' "$manifest")

        for ((i=0; i<action_count; i++)); do
            local action_id description why minutes
            action_id=$(printf "action-%03d" "$counter")
            description=$(jq -r ".post_install_actions[$i].description" "$manifest")
            why=$(jq -r ".post_install_actions[$i].why" "$manifest")
            minutes=$(jq -r ".post_install_actions[$i].estimated_minutes" "$manifest")

            echo ""
            echo "⚠ MANUAL ACTION REQUIRED — $action_id"
            echo "Action: $description"
            echo "Why: $why"
            echo "Estimated time: $minutes minutes"
            echo "→ Do you need step-by-step instructions? (y/n)"
            echo "→ Type 'done' when complete, or 'skip' to flag and continue"

            counter=$((counter + 1))
        done
    done
}
